- hosts: localhost
  become: true
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME')}}/.ssh/id_ed25519"
    projects: "{{ lookup('env', 'HOME')}}/projects"
  pre_tasks:
    - name: Update cache
      community.general.pacman:
        update_cache: true
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/core-setup.yml
    - import_tasks: tasks/utils-setup.yml
    - import_tasks: tasks/productivity-tools.yml
    - import_tasks: tasks/kitty-setup.yml
    - import_tasks: tasks/rice-setup.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/git-setup.yml
    - import_tasks: tasks/projects.yml
