- name: Setup xorg
  become_user: "{{ lookup('env', 'USER') }}"
  tags:
    - install
    - core
  block:
    - name: Install xorg packages
      community.general.pacman:
        name:
          - xorg
          - xorg-xinit
    - name: Setup .xinitrc
      ansible.builtin.copy:
        src: /etc/X11/xinit/xinitrc 
        dest: "{{ lookup('env', 'HOME') }}/.xinitrc"
    - name: Register .xinitrc content
      shell:  "cat {{ lookup('env', 'HOME') }}/.xinitrc"
      register: xinitrc_content
    - name: Remove default term and WM
      blockinfile:
        path: ~/.xinitrc
        block: "{{ xinitrc_content.stdout_lines[:-5] | join('\n') }}"
    - name: Append 'exec awesome'
      lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.xinitrc"
        line: 'exec awesome'
    - name: Check GPU vendor and install driver
      block:
        - name: Install NVIDIA driver
          community.general.pacman:
            name: nvidia
          when: "'NVIDIA Corporation' in ansible_devices['GPU']['subsystem_vendor']"
        - name: Install NVIDIA driver
          community.general.pacman:
            name: amdgpu
          when: "'Advanced Micro Devices, Inc.' in ansible_devices['GPU']['subsystem_vendor']"

- name: Setup core packages
  community.general.pacman:
    name: ["curl", "htop", "go", "ccache", "lsof", "python-pip", "python", "pavucontrol", "nvidia", "nvidia-settings", "docker"]
  tags:
    - install
    - core 
- name: Setup core packages needed for neovim
  tags:
    - install
    - core 
    - neovim
  block:
    - name: Build packages
      community.general.pacman:
        name: ["base-devel", "cmake"]
    - name: Install lua, unzip, gettext
      community.general.pacman:
        name: ["lua", "unzip", "gettext"]
    - name: Install clang
      community.general.pacman:
        name: ["clang"]


