- name: Setup xorg
  become_user: "{{ lookup('env', 'USER') }}"
  tags:
    - install
    - core
  block:
    - name: Install xorg packages:wq
      community.general.pacman:
        name:
          - xorg
          - xorg-xinit
    - name: Setup .xinitrc
      block: 
      - name: Register .xinitrc content
        become: True
        shell:  "cat /etc/X11/xinit/xinitrc"
        register: xinitrc_content
      - name: Remove default term and WM
        blockinfile:
          path: " {{ home_dir }}/.xinitrc"
          block: |
            {{ xinitrc_content.stdout_lines[:-5] | join('\n') }}
            ~/.fehbg &
            exec awesome
      - name: Append 'exec awesome'
        lineinfile:
          path: "{{ lookup('env', 'HOME') }}/.xinitrc"
          line: 'exec awesome'
      - name: Check GPU vendor and install driver
        tags:
          - gpu
        block:
        - name: Install jq and lshw
          community.general.pacman:
            name:
              - jq
              - lshw
        - name: Set gpu vendor
          shell: lshw -json | jq '.. | select(.id? == "display")| .vendor | grep -oE (nvidia|amd)'
          register: gpu_vendor
        - name: Install NVIDIA driver
          community.general.pacman:
            name: nvidia
          when: "'NVIDIA Corporation' in ansible_devices['GPU']['subsystem_vendor']"
        - name: Install NVIDIA driver
          community.general.pacman:
            name: amdgpu
          when: "'amd' in gpu_vendor"

- name: Setup core packages
  community.general.pacman:
    name: 
      - curl
      - htop
      - go
      - ccache
      - lsof
      - python-pip
      - python
      - pavucontrol
      - docker
  tags:
    - install
    - core 
- name: Setup core packages needed for neovim
  tags:
    - install
    - core 
    - neovim
  block:
    - name: Build packages
      community.general.pacman:
        name: ["base-devel", "cmake"]
    - name: Install lua, unzip, gettext
      community.general.pacman:
        name: ["lua", "unzip", "gettext"]
    - name: Install clang
      community.general.pacman:
        name: ["clang"]


