- name: Setup projects
  become_user: "{{ lookup('env', 'USER') }}"
  tags:
    - install
    - projects
  block:
    - name: Ansible exists
      stat:
        path: "{{ projects_dir }}/ansible"
      register: ansible
      tags:
        - install
        - projects
    - name: Project ansible
      ansible.builtin.git:
        repo: git@github.com:m-dziuba/ansible
        dest: "{{ projects_dir }}/ansible"
      tags:
        - install
        - projects
      when: ansible.stat.exists == False
    - name: pftui exists
      stat:
        path: "{{ projects_dir }}/pftui"
      register: pftui
      tags:
        - install
        - projects
    - name: Project ansible
      ansible.builtin.git:
        repo: git@github.com:m-dziuba/pftui
        dest: "{{ projects_dir }}/pftui"
      tags:
        - install
        - projects
      when: pftui.stat.exists == False


