- name: Setup ssh keys
  tags:
    - dotfiles
    - install
    - ssh
  block:
  - name: Install OpenSSH
    community.general.pacman:
      name: openssh
  - name: Ensure .ssh directory exists
    file: 
      dest: "{{ dest_key | dirname }}"
      mode: 0700
      state: directory
  - name: Ensure known_hosts file exists
    file:
      dest: "{{ dest_key | dirname }}/known_hosts"
      mode: 0600
      state: touch
  - name: Install ssh key private
    copy:
      src: "{{ source_key }}"
      dest: "{{ dest_key }}"
      mode: 0600
  - name: Install ssh key public
    copy:
      src: "{{ source_key }}.pub"
      dest: "{{ dest_key }}.pub"
      mode: 0644
    #  - name: Set authorized key taken from file
    #    authorized_key:
    #      user: "{{ lookup('env', 'USER') }}"
    #      state: present
    #      key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub }}"
    #    with_fileglob:
    #    - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
  - name: Change ownership of .ssh directory exists
    file: 
      dest: "{{ dest_key | dirname }}"
      mode: 0700
      state: directory
      recurse: yes
      owner: "{{ lookup('env', 'USER') }}"
