- name: Setup zsh
  tags:
  - install
  - dotfiles
  - zsh
  - productivity
  become_user: "{{ lookup('env', 'USER') }}"
  block:
  - name: Install zsh
    community.general.pacman:
      name: zsh
  - name: Install python-pexpect
    community.general.pacman:
      name: python-pexpect
  - name: Set zsh as deafult terminal
    become_user: root
    shell: chsh -s $(which zsh)
  - name: Set enviroment vars for oh-my-zsh installation
    shell: CHSH=yes
  - name: Set enviroment vars for oh-my-zsh installation
    shell: RUNZSH=yes
  - name: Install oh-my-zsh
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended 
  - name: Set ZSH_CUSTOM
    shell: "ZSH_CUSTOM="
  - name: Install the zsh-autosuggestions
    ansible.builtin.git:
      repo:  https://github.com/zsh-users/zsh-autosuggestions.git
      dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  - name: Install zsh-syntax-highlighting
    ansible.builtin.git:
      repo:  https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  - name: Install zsh powerlevel10k theme
    ansible.builtin.git:
      repo:  https://github.com/romkatv/powerlevel10k.git
      dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes/powerlevel10k"
