- name: Setup zsh
  tags:
  - install
  - dotfiles
  - zsh
  - productivity
  block:
  - name: Install zsh
    community.general.pacman:
      name: zsh
  - name: Install python-pexpect
    community.general.pacman:
      name: python-pexpect
  - name: Set enviroment vars for oh-my-zsh installation
    shell: CHSH=yes
  - name: Set enviroment vars for oh-my-zsh installation
    shell: RUNZSH=yes
  - name: Install oh-my-zsh
    become_user: "{{ lookup('env', 'USER') }}"
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended 
  - name: Install the zsh-autosuggestions
    ansible.builtin.git:
      repo:  https://github.com/zsh-users/zsh-autosuggestions.git
      dest: "{{ lookup('env', 'ZSH_CUSTOM') }}/plugins/zsh-autosuggestions"
  - name: Install zsh-syntax-highlighting
    ansible.builtin.git:
      repo:  https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: "{{ lookup('env', 'ZSH_CUSTOM') }}/plugins/zsh-syntax-highlighting"
  - name: Install zsh powerlevel10k theme
    ansible.builtin.git:
      repo:  https://github.com/romkatv/powerlevel10k.git
      dest: "{{ lookup('env', 'ZSH_CUSTOM') }}/themes/powerlevel10k"
